title: Stefan Decimelli Blog
email: stefandecimelli@gmail.com
#description: My blog!
baseurl: "/" 
url: "https://stefandecimelli.github.io/"
github_username:  stefandecimelli
linkedin_username: stefandecimelli
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.md
minima:
  skin: dark