title: Stefan is Blogging
email: stefandecimelli@gmail.com
description: Uh oh, stefan is blogging again…
baseurl: "/" 
url: "https://stefandecimelli.github.io/"
github_username:  stefandecimelli
linkedin_username: stefandecimelli
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.md
page_break: "<div style=\"margin:0;display:flex;justify-content:center;align-items:center;margin-bottom:1rem\"><div>● ● ●</div></div>"
